# Generated by Django 4.2 on 2023-05-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_type_id',
            new_name='organisation_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organisation_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.organisation'),
        ),
    ]
