# Generated by Django 4.2 on 2023-06-02 03:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0002_rename_organisation_type_id_organisation_organisation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_type_title', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type_title', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.TextField(max_length=20)),
                ('year', models.IntegerField()),
                ('make', models.TextField(max_length=20)),
                ('model', models.TextField(max_length=20)),
                ('fuel', models.TextField(max_length=20)),
                ('output', models.IntegerField()),
                ('drivetrain', models.TextField(max_length=20)),
                ('trim_line', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('import_as', models.TextField(max_length=4)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('policy_type', models.TextField(max_length=100)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.IntegerField()),
                ('punishment', models.TextField(max_length=100)),
                ('due_date', models.DateField(default=datetime.datetime.now)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('breach_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.breachtype')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('new_owner', models.TextField(max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('new_plates', models.TextField(max_length=30)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('products_used', models.TextField(max_length=500)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('maintenance_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.maintenancetype')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('detail', models.TextField(blank=True, max_length=400)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('import_as', models.TextField(default='', max_length=4)),
                ('damaged', models.TextField(default='', max_length=3)),
                ('milage', models.IntegerField()),
                ('country_of_origin', models.TextField(blank=True, max_length=30)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('other_participants', models.TextField(max_length=3)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle')),
            ],
        ),
    ]
