# Generated by Django 4.2 on 2023-06-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0003_breachtype_maintenancetype_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organisation',
        ),
    ]
