# Generated by Django 4.2 on 2023-06-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0006_auto_20230602_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidentrecord',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='customrecord',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='financerecord',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='numberplate',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='policyrecord',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='registrationrecord',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RemoveField(
            model_name='registrationrecord',
            name='import_as',
        ),
    ]
