# Generated by Django 4.2 on 2023-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0007_rename_milage_accidentrecord_mileage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomRecord',
            new_name='CustomsRecord',
        ),
        migrations.RemoveField(
            model_name='financerecord',
            name='detail',
        ),
        migrations.AddField(
            model_name='financerecord',
            name='actual_completion_date',
            field=models.DateField(null=True),
        ),
    ]
