# Generated by Django 4.2 on 2023-06-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0008_rename_customrecord_customsrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunishmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment_type_title', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='policerecord',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='policerecord',
            name='punishment',
        ),
        migrations.AddField(
            model_name='policerecord',
            name='punishment_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.punishmenttype'),
        ),
    ]
