# Generated by Django 4.2 on 2023-06-03 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0009_punishmenttype_remove_policerecord_fine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policerecord',
            name='record_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
