# Generated by Django 4.2 on 2023-06-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0010_policerecord_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='expiry_date',
        ),
    ]
