# Generated by Django 4.2 on 2023-06-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0014_rename_vehicle_ownership_vehicle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
