# Generated by Django 4.2 on 2023-06-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0015_rename_vehicle_id_ownership_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle'),
        ),
    ]
