# Generated by Django 4.2 on 2023-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0016_alter_ownership_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='vehicle',
            new_name='vehicle_id',
        ),
    ]
