# Generated by Django 4.2 on 2023-06-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0018_rename_user_id_ownership_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='ownership',
            name='vehicle_id',
            field=models.ForeignKey(db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle'),
        ),
    ]
