# Generated by Django 4.2 on 2023-06-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0019_rename_user_ownership_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.vehicle'),
        ),
    ]
