# Generated by Django 4.2 on 2023-06-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0020_alter_ownership_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='ownership',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='VehicleHub.vehicle'),
        ),
    ]
