# Generated by Django 4.2 on 2023-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0023_financerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentrecord',
            name='other_participants',
            field=models.TextField(max_length=80, null=True),
        ),
    ]
