# Generated by Django 4.2 on 2023-06-13 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0024_alter_accidentrecord_other_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registred_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
