# Generated by Django 4.2 on 2023-06-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0025_vehicle_registred_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='registred_owner',
            new_name='registred_owner_user_id',
        ),
    ]
