# Generated by Django 4.2 on 2023-06-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0026_rename_registred_owner_vehicle_registred_owner_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrecord',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='registrationrecord',
            name='vehicle_id',
        ),
        migrations.DeleteModel(
            name='PolicyRecord',
        ),
        migrations.DeleteModel(
            name='RegistrationRecord',
        ),
    ]
