# Generated by Django 4.2 on 2023-06-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0027_remove_registrationrecord_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='registred_owner_user_id',
            new_name='registered_owner_user_id',
        ),
    ]
