# Generated by Django 4.2 on 2023-06-21 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0031_vehiclemake_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsrecord',
            name='country_of_origin',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='policerecord',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
