# Generated by Django 4.2 on 2023-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0035_rename_vehicle_ownership_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField()),
            ],
        ),
    ]
