# Generated by Django 4.2 on 2023-06-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0036_safetyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rating',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='VehicleHub.safetyrating'),
            preserve_default=False,
        ),
    ]
