# Generated by Django 4.2 on 2023-06-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0038_rename_raiting_safetyrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='new_plates',
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
