# Generated by Django 4.2 on 2023-06-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleHub', '0039_alter_numberplate_new_plates_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='products_used',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
